---
title: "Project Data Analysis"
output: html_document
date: "2023-01-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Packages
```{r load packages, include=FALSE}
library(tidyverse)
```

# Create a site lookup table
```{r create a site lookup table}
# create plot / site lookup table
lookup_table <- data.frame(
  Plot = c("3", "4", "5", "6", "7", "8", "9", "10", "11", "13", "18", "24", "24"),
  site = c("103", "104", "105", "106", "107", "108", "209", "110", "111", "113", "301", "104", "104 S"),
  fire_frequency = c("0.8", "0.8", "0.5", "0.667", "0.333", "0.333", "0", "0", "0.1", "0.1", "0", "0.8", "0.8")
)
```

# Load and process mycorrhizal dataset
```{r}
# main datasets
mycorrhizal_data <- read_csv("../data-raw/mycorrhizal_data.csv")

# adjust column types
mycorrhizal_data$intrhyphae <- as.numeric(mycorrhizal_data$intrhyphae)
mycorrhizal_data$fire_frequency <- as.numeric(mycorrhizal_data$fire_frequency)
mycorrhizal_data$site <- as.character(mycorrhizal_data$site)

# add a new column "percentage success", which takes the number of non-NA values per 100 rows and divides by 100
mycorrhizal_data <- mycorrhizal_data %>% 
  mutate(group = as.integer(row_number()/100)) %>%
  group_by(group) %>%
  mutate(percentage.mycorrhizal.success = sum(!is.na(spore))/n()) %>%
  ungroup()

# only include successful mycorrhizal stains
mycorrhizal_data <- filter(mycorrhizal_data, `staining_success` == "Y")

# make presence column, which is 1 if any AMF structure is present and 0 if no AMF structures are present
mycorrhizal_data$presence <- ifelse(rowSums(mycorrhizal_data[,c("hyphopodia", "intrhyphae", "arbuscule", "coil", "vesicle", "spore")]) > 0, 1, 0)

# create a summarised dataset, where each observation is a uniqe species / site combination
mycorrhizal_data_summarised <- mycorrhizal_data %>%
  group_by(site, species) %>%
  summarise(mean_colonisation = mean(presence),
            fire_frequency = first(fire_frequency),
            percentage.mycorrhizal.success = first(percentage.mycorrhizal.success),
            functional_group = first(functional_group))

## multiply decimal values by 100 to get a percentage
mycorrhizal_data_summarised$mean_colonisation <- mycorrhizal_data_summarised$mean_colonisation*100 

# export processed dataset
write_csv(mycorrhizal_data_summarised, "../data/mycorrhizal_data_summarised")
```

# Load and Process Nitrogen Dataset
```{r load and process nitrogen dataset}
nitrogen <- read_csv("../data-raw/nitrogen.csv")
write_csv(nitrogen, "../data/nitrogen.csv")

#change column name
nitrogen$site <- nitrogen$Burn.Unit

# summarise dataset
nitrogen_summarised <- nitrogen %>%
  group_by(site) %>%
  summarise(mean_inorganic_N = mean(TotalINmgperg))

nitrogen_summarised <- nitrogen_summarised[-2,]
nitrogen_summarised[2,1] <- "104"

#export dataset
write_csv(nitrogen_summarised, "../data/nitrogen_summarised")
```

# Load and process Phosphorous Dataset
```{r load and process phosphorous dataset}
# phosphorous dataset
phosphorous <- read_csv("../data-raw/phosphorous.csv")
phosphorous <- rename(phosphorous, soil_phosphate = P, site = Burn.Unit, fire_frequency = Fire)

# select only the relevant columns and rows and remove NAs. 20cm depth makes comparable to nitrogen
phosphorous <- select(phosphorous, site, Deepest, soil_phosphate, fire_frequency)
phosphorous <- filter(phosphorous, Deepest <= 20)
phosphorous <- na.omit(phosphorous)

write_csv(phosphorous, "../data/phosphorous.csv")

# summarise phosphorous data, taking the mean phosphate values for each burn unit (site)
phosphorous_summarised <- phosphorous %>%
  group_by(site) %>%
  summarise(mean.soil_phosphate = mean(soil_phosphate))

# remove 104N as only took from 104S, and rename as 104
phosphorous_summarised <- phosphorous_summarised[-2,]
phosphorous_summarised[2,1] <- "104"

write_csv(phosphorous_summarised, "../data/phosphorous_summarised")
```

# Load and Process Root Datasets
```{r load and process root datasets}
# root traits dataset
root_traits <- read_csv("../data-raw/root_traits.csv")
root_mass <- read_csv("../data-raw/root_mass.csv")

# process root traits dataset
root_traits$site <- as.character(root_traits$site)
root_traits <- filter(root_traits, Success == "Y")
root_traits_summarised <- root_traits %>%
  group_by(site, species) %>%
  summarise_all(mean)
root_traits_summarised <- select(root_traits_summarised, c("site", "species", "total_root_length_mm", "average_diameter_mm", "volume_mm3"))

# process root mass dataset
root_mass$dry_mass <- root_mass$dry_mass_dish - root_mass$tin_mass
root_mass$wet_mass <- root_mass$wet_mass_dish - root_mass$tin_mass
root_mass$site <- as.character(root_mass$site)

# combine root traits and root mass datasets
root_traits_summarised$dry_mass <- NA

for (i in 1:nrow(root_traits_summarised)) {
  site_species <- paste(root_traits_summarised$species[i], root_traits_summarised$site[i])
  match_row <- which(paste(root_mass$species, root_mass$site) == site_species)
  if (length(match_row) == 1) {
    root_traits_summarised$dry_mass[i] <- root_mass$dry_mass[match_row]
  } else {
    # handle cases where there are multiple matches or no matches
    # e.g. by assigning NA or taking the average of dry_mass values
  }
}

# process root dataset to include SRL and root tissue density
root_traits_summarised$total_root_length_m <- root_traits_summarised$total_root_length_mm / 1000
root_traits_summarised$SRL <- root_traits_summarised$total_root_length_m / root_traits_summarised$dry_mass
root_traits_summarised$Volume.cm3 <- root_traits_summarised$volume_mm3 / 1000
root_traits_summarised$RTD <- root_traits_summarised$dry_mass / root_traits_summarised$Volume.cm3

root_data <- root_traits_summarised %>%
  merge(lookup_table, by = "site")

write_csv(root_data, "../data/root_data")
```

# Load and Process Cover Dataset
```{r}
cover <- read_csv("../data-raw/percent cover.csv")

cover <- cover %>%
  filter(Year == "2021") %>%
  group_by(Plot) %>%
  mutate(total_cover = sum(MeanPctCover)) %>%
  mutate(relative_cover = MeanPctCover / total_cover * 100) %>%
  select(c("Plot", "Lifeform", "GenusSpecies", "relative_cover", "Realfire"))

cover$Plot <- as.character(cover$Plot)
cover$species <- cover$GenusSpecies
cover <- cover %>%
  full_join(lookup_table, by = "Plot")

write_csv(cover, "../data/cover.csv")
```

# Load and Light and Biomass Dataset
```{r}
biomass_light_data <- read_csv("../data-raw/biomass_light_data.csv")

biomass_light_data <- biomass_light_data %>%
  subset(Year == 2021) %>%
  select(c("Burn.Unit", "Herbbiommodel", "mLightUptakeHerb"))
  
biomass_light_data$site <- biomass_light_data$Burn.Unit
biomass_light_data$biomass <- biomass_light_data$Herbbiommodel
biomass_light_data$light_uptake <- biomass_light_data$mLightUptakeHerb

biomass_light_data <- biomass_light_data %>%
  full_join(lookup_table, by = "site")

biomass_light_data <- na.omit(biomass_light_data)

write_csv(biomass_light_data, "../data/biomass_light_data")
```

# Combining Datasets
```{r combine datasets}
## combine root traits, mycorrhizal and phosphorous datasets
nutrients_combined <- full_join(phosphorous_summarised, nitrogen_summarised, by = "site")

cover_indices <- match(paste(mycorrhizal_data_summarised$species, mycorrhizal_data_summarised$site), paste(cover$species, cover$site))
mycorrhizal_data_summarised$relative_cover <- cover$relative_cover[cover_indices]

root_indices <- match(paste(mycorrhizal_data_summarised$species, mycorrhizal_data_summarised$site), paste(root_data$species, root_data$site))
mycorrhizal_data_summarised$RTD <- root_data$RTD[root_indices]
mycorrhizal_data_summarised$average_diameter_mm <- root_data$average_diameter_mm[root_indices]
mycorrhizal_data_summarised$SRL <- root_data$SRL[root_indices]

data_combined <- merge(mycorrhizal_data_summarised, nutrients_combined, all = TRUE)

data_combined <- filter(data_combined, mean_colonisation >= 0)

write_csv(data_combined, "../data/data_combined")
```



