---
title: "Project Data Analysis"
output: html_document
date: "2023-01-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages and read in data, include=FALSE}
library(tidyverse)
library(ggpubr)
library(FactoMineR)
library(factoextra)

# mycorrhizae datasets
data <- read_csv("Datasets/data.csv")

# root traits dataset
root_traits <- read_csv("Datasets/root_traits.csv")

#root mass dataset
root_mass <- read_csv("Datasets/root_mass.csv")

# phosphorous dataset
phosphorous <- read_csv("Datasets/phosphorous.csv")

# soil inorganic nitrogen dataset
nitrogen <- read_csv("Datasets/nitrogen.csv")

#percent cover dataset
cover <- read_csv("Datasets/percent cover.csv")

# create plot / site lookup table
lookup_table <- data.frame(
  Plot = c("3", "4", "5", "6", "7", "8", "9", "10", "11", "13", "18", "24"),
  site = c("103", "104", "105", "106", "107", "108", "209", "110", "111", "113", "109", "104"),
  fire_frequency = c("0.8", "0.8", "0,5", "0.667", "0.333", "0.333", "0", "0", "0.1", "0.1", "0", "0.8")
)
```

```{r make publication colour theme, include=FALSE}
theme_Publication <- function(base_size=14, base_family="helvetica") {
      library(grid)
      library(ggthemes)
      (theme_foundation(base_size=base_size, base_family=base_family)
       + theme(plot.title = element_text(face = "bold",
                                         size = rel(1.2), hjust = 0.5),
               text = element_text(),
               panel.background = element_rect(colour = NA),
               plot.background = element_rect(colour = NA),
               panel.border = element_rect(colour = NA),
               axis.title = element_text(face = "bold",size = rel(1)),
               axis.title.y = element_text(angle=90,vjust =2),
               axis.title.x = element_text(vjust = -0.2),
               axis.text = element_text(), 
               axis.line = element_line(colour="black"),
               axis.ticks = element_line(),
               panel.grid.major = element_line(colour="#f0f0f0"),
               panel.grid.minor = element_blank(),
               legend.key = element_rect(colour = NA),
               legend.position = "bottom",
               legend.direction = "horizontal",
               legend.key.size= unit(0.2, "cm"),
               legend.margin = unit(0, "cm"),
               legend.title = element_text(face="italic"),
               plot.margin=unit(c(10,5,5,5),"mm"),
               strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
               strip.text = element_text(face="bold")
          ))
      
}

scale_fill_Publication <- function(...){
      library(scales)
      discrete_scale("fill","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}

scale_colour_Publication <- function(...){
      library(scales)
      discrete_scale("colour","Publication",manual_pal(values = c("#386cb0","#fdb462","#7fc97f","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3","#ffff33")), ...)

}
```

```{r inspect data, make sure columns are the correct type and name, include = FALSE}

# correct value types in data
summary(data)
data$intrhyphae <- as.numeric(data$intrhyphae)
data$fire_frequency <- as.numeric(data$fire_frequency)
data$site <- as.character(data$site)

# correct column type in root data
summary(root_traits)
root_traits$site <- as.character(root_traits$site)

# rename columns in phosphate data
summary(phosphorous)
phosphorous <- rename(phosphorous, soil_phosphate = P, site = Burn.Unit)

# process root mass dataset
root_mass$dry_mass <- root_mass$dry_mass_dish - root_mass$tin_mass
root_mass$wet_mass <- root_mass$wet_mass_dish - root_mass$tin_mass
root_mass$site <- as.character(root_mass$site)

# process percent cover dataset
cover <- cover %>%
  filter(Year == "2021") %>%
  group_by(Plot) %>%
  mutate(total_cover = sum(MeanPctCover)) %>%
  mutate(relative_cover = MeanPctCover / total_cover * 100) %>%
  select(c("Plot", "Lifeform", "GenusSpecies", "relative_cover", "Realfire"))

cover$Plot <- as.character(cover$Plot)
cover$species <- cover$GenusSpecies
cover <- cover %>%
  full_join(lookup_table, by = "Plot")
```

```{r add percentage success column and remove unsuccessful samples}

# add a new column "percentage success", which takes the number of non-NA values per 100 rows and divides by 100
data <- data %>% 
  mutate(group = as.integer(row_number()/100)) %>%
  group_by(group) %>%
  mutate(percentage.mycorrhizal.success = sum(!is.na(spore))/n()) %>%
  ungroup()
  
# only include successful mycorrhizal stains
data <- filter(data, `staining_success` == "Y")

 # only include successful root trait analyses
root_traits <- filter(root_traits, Success == "Y")

# select only the relevant columns and rows and remove NAs. 20cm depth makes comparable to nitrogen
phosphorous <- select(phosphorous, site, Deepest, soil_phosphate, Fire)
phosphorous <- filter(phosphorous, Deepest <= 20)
phosphorous <- na.omit(phosphorous)
phosphorous$fire_frequency <- phosphorous$Fire
```

```{r summarising main dataset}

# make presence column, which is 1 if any AMF structure is present and 0 if no AMF structures are present
data$presence <- ifelse(rowSums(data[,c("hyphopodia", "intrhyphae", "arbuscule", "coil", "vesicle", "spore")]) > 0, 1, 0)

# make sure presence column is numeric
data$presence <- as.numeric(data$presence)

# create a summarised dataset, where each observation is a uniqe species / site combination
data_summarised <- data %>%
  group_by(site, species) %>%
  summarise(mean_colonisation = mean(presence),
            fire_frequency = first(fire_frequency),
            percentage.mycorrhizal.success = first(percentage.mycorrhizal.success),
            light_uptake_herb = first(light_uptake_herb),
            percent_cover = first(percent_cover),
            soil_inorganic_nitrogen = first(soil_inorganic_nitrogen),
            functional_group = first(functional_group))

## multiply decimal values by 100 to get a percentage
data_summarised$mean_colonisation <- data_summarised$mean_colonisation*100 

# create separate semi-summarised dataset, where each observation is a root section instead of a root sample (pseudoreplication)
data_section_summarised <- data %>%
  group_by(site, replicate_number_root) %>%
  summarise(mean_colonisation = mean(presence),
            species = first(species),
            fire_frequency = first(fire_frequency),
            percentage.mycorrhizal.success = first(percentage.mycorrhizal.success),
            light_uptake_herb = first(light_uptake_herb),
            percent_cover = first(percent_cover),
            soil_inorganic_nitrogen = first(soil_inorganic_nitrogen),
            functional_group = first(functional_group))

## multiply decimal values by 100 to get a percentage
data_section_summarised$mean_colonisation <- data_section_summarised$mean_colonisation*100 

# summarise nitrogen dataset
nitrogen$site <- nitrogen$Burn.Unit
nitrogen_summarised <- nitrogen %>%
  group_by(site) %>%
  summarise(mean_inorganic_N = mean(TotalINmgperg))
```

```{r summarise root dataset}

# first group by site and species (encodes unique value), then take the mean of each column for every unique site and species combination
root_traits_summarised <- root_traits %>%
  group_by(site, species) %>%
  summarise_all(mean)

# keep only relevant columns for future analysis
root_traits_summarised <- select(root_traits_summarised, c("site", "species", "total_root_length_mm", "average_diameter_mm", "volume_mm3"))
```

```{r summarise phosphate dataset}

# summarise phosphorous data, taking the mean phosphate values for each burn unit (site)
phosphorous_summarised <- phosphorous %>%
  group_by(site) %>%
  summarise(mean.soil_phosphate = mean(soil_phosphate))

#remove 104N as only took from 104S
phosphorous_summarised <- phosphorous_summarised[-2,]
phosphorous_summarised[2,1] <- "104"
```

```{r combine datasets}
# combine root traits and root mass datasets
root_data <- full_join(root_mass, root_traits_summarised, by = c("site", "species"))
# process root dataset to include SRL and root tissue density
root_data$Total.Root.Length.m <- root_data$total_root_length_mm / 1000
root_data$SRL <- root_data$Total.Root.Length.m / root_data$dry_mass
root_data$Volume.cm3 <- root_data$volume_mm3 / 1000
root_data$RTD <- root_data$dry_mass / root_data$Volume.cm3

# for sample summarised dataset
## combine root traits, mycorrhizal and phosphorous datasets
data_combined <- full_join(root_data, data_summarised, by = c("species", "site")) 
data_combined <- full_join(data_combined, phosphorous_summarised, by = "site")
data_combined <- left_join(data_combined, cover, by = c("species", "site"))
data_combined <- filter(data_combined, mean_colonisation > 0)

# for section summarised dataset
data_section_combined <- full_join(root_data, data_section_summarised, by = c("species", "site"))
data_section_combined <- full_join(data_section_combined, phosphorous_summarised, by = "site")
data_section_combined <- left_join(data_section_combined, cover, by = c("species", "site"))
```

```{r plot mycorrrhizal sample data}
# general model
data_section_cleaned <- na.omit(data_section_combined)
data_section_cleaned$species <- as.character(data_section_cleaned$species)

model <- lm(mean_colonisation ~ fire_frequency.x + RTD + average_diameter_mm + SRL + soil_inorganic_nitrogen + mean.soil_phosphate + species, data = data_section_cleaned)
summary(model)
anova(model)

# plot for just poa pratensis semi-summarised
data_section_poa <- filter(data_section_summarised, species == "Poa pratensis")
fit_poa <- lm(mean_colonisation ~ fire_frequency, data = data_section_poa)
p1_poa <- ggplot(data_section_poa, aes(x=fire_frequency, y=mean_colonisation)) + 
  geom_point() + 
  stat_smooth(method = "lm") + 
  geom_label(aes(x = 0.1, y = 60), hjust = 0, 
             label = paste("Adj R2 = ",signif(summary(fit_poa)$adj.r.squared, 5), 
                           "\nIntercept =",signif(fit_poa$coef[[1]],5 ), 
                           " \nSlope =",signif(fit_poa$coef[[2]], 5), 
                           " \nP =",signif(summary(fit_poa)$coef[2, 4], 5))) +
  ylab("Average mycorrhizal colonisation (% of root)") +
  xlab("Fire frequency (Average Number of Fires / Year") + theme_pubclean() + scale_colour_Publication()
print(p1_poa)

# plot for just Amphicarpa bracteata semi-summarised
data_section_amph <- filter(data_section_summarised)
fit_amph <- lm(mean_colonisation ~ fire_frequency, data = data_section_amph)
p1_amph <- ggplot(data_section_amph, aes(x=fire_frequency, y=mean_colonisation)) + 
  geom_point() + 
  stat_smooth(method = "lm") + 
  geom_label(aes(x = 0.1, y = 75), hjust = 0, 
             label = paste("Adj R2 = ",signif(summary(fit_amph)$adj.r.squared, 5), 
                           "\nIntercept =",signif(fit_amph$coef[[1]],5 ), 
                           " \nSlope =",signif(fit_amph$coef[[2]], 5), 
                           " \nP =",signif(summary(fit_amph)$coef[2, 4], 5))) +
    ylab("Average mycorrhizal colonisation (% of root)") +
    xlab("Fire frequency (Average Number of Fires / Year") + theme_pubclean() + scale_colour_Publication()
print(p1_amph)
```

```{r plot soil nutrient data}
# change this to be for wider dataset, not just ones I have mycorrhizal data on

#plot soil nitrogen against fire frequency
nit_model <- lm(TotalINmgperg ~ Fire, data = nitrogen)
p1_nit <- ggplot(nitrogen, aes(x=Fire, y=TotalINmgperg)) + 
  geom_point() + 
  stat_smooth(method = "lm") + 
  geom_label(aes(x = 0.5, y = 0.005), hjust = 0, 
             label = paste("Adj R2 = ",signif(summary(nit_model)$adj.r.squared, 5), 
                           "\nIntercept =",signif(nit_model$coef[[1]],5 ), 
                           " \nSlope =",signif(nit_model$coef[[2]], 5), 
                           " \nP =",signif(summary(nit_model)$coef[2, 4], 5))) +
  ylab("Soil Inorganic Nitrogen") +
  xlab("Fire Frequency (Number of Fires / Year)") + theme_pubclean() + scale_colour_Publication()
print(p1_nit)

# plot soil phosphate against fire frequency
phos_model <- lm(soil_phosphate ~ fire_frequency, data = phosphorous)
p1_phos <- ggplot(phosphorous, aes(x=fire_frequency, y=soil_phosphate)) + 
  geom_point() + 
  stat_smooth(method = "lm") + 
  geom_label(aes(x = 0.05, y = 0.06), hjust = 0, 
             label = paste("Adj R2 = ",signif(summary(phos_model)$adj.r.squared, 5), 
                           "\nIntercept =",signif(phos_model$coef[[1]],5 ), 
                           " \nSlope =",signif(phos_model$coef[[2]], 5), 
                           " \nP =",signif(summary(phos_model)$coef[2, 4], 5))) +
  ylab("Soil Phosphate") +
  xlab("Fire Frequency (Number of Fires / Year)") + theme_pubclean() + scale_colour_Publication()
print(p1_phos)
```

```{r plot mycorrhizal colonisation per species}
data_species <- data_combined %>%
  group_by(species) %>%
  summarise(avg_colonisation = mean(mean_colonisation),
            functional_group = first(functional_group))
  
# plot the average mycorrhizal colonisation per species
ggplot(data_species, aes(x=species, y=avg_colonisation, fill = functional_group)) + 
  geom_bar(stat="identity") + 
  xlab("Species") +
  ylab("Average AMF Colonisation (% of Root)") +
  coord_flip() + 
  theme_pubclean() + 
  scale_fill_Publication()
```

```{r plot mycorrhizal colonisation against root traits}
# plot mycorrhizal colonisation against average root diameter
ggplot(data_section_cleaned, aes(x=average_diameter_mm, y=mean_colonisation, color = species)) +
  geom_point() +
  xlab("Average Root Diameter (mm)") +
  ylab("Average AMF Colonisation (%)") + theme_pubclean() + scale_fill_Publication()
# Variation seems to mostly interspecific
```
```{r plot community composition change}
ggplot(data_combined, aes(x = fire_frequency.y, y = relative_cover, fill = species)) +
  geom_bar(position = "dodge", stat = "identity") +
  labs(x = "Fire Frequency", y = "Relative Cover") +
  theme_pubclean() + scale_colour_Publication()
```


```{r principle component analysis}
pca_data_section <- na.omit(data_section_combined)

pca_data_section[] <- lapply(pca_data_section, as.numeric)

pca_data_section$SIN <- pca_data_section$soil_inorganic_nitrogen
pca_data_section$SP <- pca_data_section$mean.soil_phosphate
pca_data_section$AMF <- pca_data_section$mean_colonisation
pca_data_section$FF <- pca_data_section$fire_frequency.y
pca_data_section$LU <- pca_data_section$light_uptake_herb 
pca_data_section$RD <- pca_data_section$average_diameter_mm

vars <- c("RD", "SRL", "RTD", "AMF", "FF", "LU", "SIN", "SP")
# mycorrhizal colonisation and average root diaeter, as well as soil inorganic nitrogen don't contribute to the variance in the data

pca_data_section[, vars] <- scale(pca_data_section[, vars])

pca_section <- PCA(scale(pca_data_section[, vars]), scale.unit = TRUE, ncp = 5, graph = FALSE)

fviz_pca_biplot(pca_section, col.var = "contrib", col.ind = "gray", gradient.cols = c("#386cb0","#7fc97f","#ef3b2c"), 
                repel = TRUE, addEllipses = TRUE, label = "var") + ggplot2::theme(plot.title = "PCA") + theme_pubclean() + scale_fill_Publication()
```

```{r plot root traits against soil nutrients, eval=FALSE, include=FALSE}
nitrogen$site <- nitrogen$Burn.Unit 
root_traits$site <- as.character(root_traits$site)
nutrient_roots <- full_join(root_data, phosphorous_summarised, by = "site")
nutrient_roots <- full_join(nutrient_roots, nitrogen_summarised, by = "site")
nutrient_roots <- na.omit(nutrient_roots)

diameter_nutrients_model <- lm(average_diameter_mm ~ mean.soil_phosphate + mean_inorganic_N + species, data = nutrient_roots)
summary(diameter_nutrients_model)
anova(diameter_nutrients_model)
#no significant effect of nutrients on root diameter

SRL_nutrients_model <- lm(SRL ~ mean.soil_phosphate + mean_inorganic_N + species, data = nutrient_roots)
summary(SRL_nutrients_model)
anova(SRL_nutrients_model)
# soil phosphate is a predictor of SRL

cor.test(nutrient_roots$SRL, nutrient_roots$mean.soil_phosphate)
```

