---
title: "Figures"
output: html_document
date: "2023-02-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
source("../R/publication_theme.R")
```

# Read in processed datasets
```{r read in processed datasets}
data_combined <- read_csv("../data/data_combined")
cover <- read_csv("../data/cover.csv")
nitrogen <- read_csv("../data/nitrogen.csv")
nitrogen_summarised <- read_csv("../data/nitrogen_summarised")
phosphorous_summarised <- read_csv("../data/phosphorous_summarised")
phosphorous <- read_csv("../data/phosphorous.csv")
root_data <- read_csv("../data/root_data")
```

# Full Model
```{r}
fit_full <- lm(mean_colonisation ~ fire_frequency + functional_group + RTD + average_diameter_mm + SRL + mean.soil_phosphate + mean_inorganic_N, data = data_combined)
summary(fit_full)
anova(fit_full)
#step_model <- step(fit_full)
#summary(step_model)
#anova(step_model)
```

# Plot number of species
```{r}
species_count <- data.frame(table(data_combined$species))
species_count <- species_count[order(species_count$Freq), ]
range_fire_frequency <- c(1, 1, 1, 1, 1, 2, 2, 4)

species_samples <- ggplot(data = species_count, aes(x = reorder(Var1, Freq), y = Freq, fill = range_fire_frequency)) +
  geom_bar(stat = "identity") +
  coord_flip() + 
  ylab("Number of samples") +
  xlab("Species") +
  labs(fill = "Number of fire \nfrequencies (max = 6)") +
  scale_fill_gradient(low = "light blue", high = "dark blue", limits = c(0, 6)) +
  ggtitle("Number of Samples and Fire Frequencies for Each Species") +
  theme_pubclean()
print(species_samples)
```

# Plot mycorrhizal colonisation data
```{r plot mycorrrhizal sample data}
# general model
fit_all <- lm(mean_colonisation ~ fire_frequency, data = data_combined)
p1_all <- ggplot(data_combined, aes(x=fire_frequency, y=mean_colonisation)) + 
  geom_point() + 
  stat_smooth(method = "lm") + 
  geom_label(aes(x = 0, y = 60), hjust = 0, 
             label = paste("Adj R2 = ",signif(summary(fit_all)$adj.r.squared, 5), 
                           "\nIntercept =",signif(fit_all$coef[[1]],5 ), 
                           " \nSlope =",signif(fit_all$coef[[2]], 5), 
                           " \np =",signif(summary(fit_all)$coef[2, 4], 5),
                           "\nn = 17")) +
  ylab("Average mycorrhizal colonisation (% of root)") +
  xlab("Fire frequency (Average Number of Fires / Year") + 
  ggtitle("AMF Colonisation Against Fire Frequency for All Species") +
  theme_pubclean() + 
  scale_colour_Publication()
print(p1_all)

# plot for just poa pratensis
data_poa <- filter(data_combined, species == "Poa pratensis")
fit_poa <- lm(mean_colonisation ~ fire_frequency, data = data_poa)
p1_poa <- ggplot(data_poa, aes(x=fire_frequency, y=mean_colonisation)) + 
  geom_point() + 
  stat_smooth(method = "lm") + 
  geom_label(aes(x = 0, y = 60), hjust = 0, 
             label = paste("Adj R2 = ",signif(summary(fit_poa)$adj.r.squared, 5), 
                           "\nIntercept =",signif(fit_poa$coef[[1]],5 ), 
                           " \nSlope =",signif(fit_poa$coef[[2]], 5), 
                           " \np =",signif(summary(fit_poa)$coef[2, 4], 5),
                           "\nn = 6")) +
  ylab("Average mycorrhizal colonisation (% of root)") +
  xlab("Fire frequency (Average Number of Fires / Year") + 
  ggtitle(expression(paste("AMF Colonisation Against Fire Frequency for", italic(" P. pratensis")))) +
  theme_pubclean() + 
  scale_colour_Publication()
print(p1_poa)

# plot for just Amphicarpa bracteata
data_amph <- filter(data_combined, species == "Amphicarpa bracteata")
fit_amph <- lm(mean_colonisation ~ fire_frequency, data = data_amph)
p1_amph <- ggplot(data_amph, aes(x=fire_frequency, y=mean_colonisation)) + 
  geom_point() + 
  stat_smooth(method = "lm") + 
  geom_label(aes(x = 0., y = 75), hjust = 0, 
             label = paste("Adj R2 = ",signif(summary(fit_amph)$adj.r.squared, 5), 
                           "\nIntercept =",signif(fit_amph$coef[[1]],5 ), 
                           " \nSlope =",signif(fit_amph$coef[[2]], 5), 
                           " \np =",signif(summary(fit_amph)$coef[2, 4], 5),
                           "\nn = 4")) +
    ylab("Average mycorrhizal colonisation (% of root)") +
    xlab("Fire frequency (Average Number of Fires / Year") + 
    ggtitle(expression(paste("AMF Colonisation Against Fire Frequency for", italic(" A. bracteata")))) +
    theme_pubclean() + 
    scale_colour_Publication()
print(p1_amph)

# Plot for grasses
data_grass <- filter(data_combined, functional_group == "grass")
fit_grass <- lm(mean_colonisation ~ fire_frequency, data = data_grass)
p1_grass <- ggplot(data_grass, aes(x=fire_frequency, y=mean_colonisation)) + 
  geom_point() + 
  stat_smooth(method = "lm") + 
  geom_label(aes(x = 0., y = 50), hjust = 0, 
             label = paste("Adj R2 = ",signif(summary(fit_grass)$adj.r.squared, 5), 
                           "\nIntercept =",signif(fit_grass$coef[[1]],5 ), 
                           " \nSlope =",signif(fit_grass$coef[[2]], 5), 
                           " \np =",signif(summary(fit_grass)$coef[2, 4], 5),
                           "\nn = 10")) +
    ylab("Average mycorrhizal colonisation (% of root)") +
    xlab("Fire frequency (Average Number of Fires / Year") + 
    ggtitle(expression(paste("AMF Colonisation Against Fire Frequency for Grasses"))) +
    theme_pubclean() + 
    scale_colour_Publication()
print(p1_grass)


# Plot for Poa pratensis and Amphicarpa bracteata
data_amph_poa <- filter(data_combined, species == "Amphicarpa bracteata" | species == "Poa pratensis")
fit_amph_poa <- lm(mean_colonisation ~ fire_frequency, data = data_amph_poa)
p1_amph_poa <- ggplot(data_amph_poa, aes(x=fire_frequency, y=mean_colonisation, colour = species)) + 
  geom_point() + 
  stat_smooth(method = "lm") + 
    ylab("Average mycorrhizal colonisation (% of root)") +
    xlab("Fire frequency (Average Number of Fires / Year") + 
    geom_label(aes(x = 0., y = 75), hjust = 0, 
             label = paste("Adj R2 = ",signif(summary(fit_amph_poa)$adj.r.squared, 5), 
                           "\nIntercept =",signif(fit_amph_poa$coef[[1]],5 ), 
                           " \nSlope =",signif(fit_amph_poa$coef[[2]], 5), 
                           " \np =",signif(summary(fit_amph_poa)$coef[2, 4], 5),
                           "\nn = 4")) +
    ggtitle(expression(paste("AMF Colonisation Against Fire Frequency for", italic(" A. bracteata"), " and", italic(" P. pratensis")))) +
    theme_pubclean() + 
    scale_colour_Publication()
print(p1_amph_poa)
```

# Plot relationship between soil nutrients and fire frequency from publications
```{r plot soil nutrient data}
#plot soil nitrogen against fire frequency
nit_model <- lm(TotalINmgperg ~ fire_frequency, data = nitrogen)
p1_nit <- ggplot(nitrogen, aes(x=fire_frequency, y=TotalINmgperg)) + 
  geom_point() + 
  stat_smooth(method = "lm") + 
  geom_label(aes(x = 0.01, y = 0.005), hjust = 0, 
             label = paste("Adj R2 = ",signif(summary(nit_model)$adj.r.squared, 5), 
                           "\nIntercept =",signif(nit_model$coef[[1]],5 ), 
                           " \nSlope =",signif(nit_model$coef[[2]], 5), 
                           " \np =",signif(summary(nit_model)$coef[2, 4], 5),
                           "\nn = 87")) +
  ylab(expression(paste("Soil Inorganic Nitrogen (", mgNgsoil^-1, ")", sep = ""))) +
  xlab("Fire Frequency (Number of Fires / Year)") + 
  ggtitle("Soil Inorganic Nitrogen Against Fire Frequency for All Sites") +
  theme_pubclean()
  
print(p1_nit)

# plot soil phosphate against fire frequency
phos_model <- lm(soil_phosphate ~ fire_frequency, data = phosphorous)
p1_phos <- ggplot(phosphorous, aes(x=fire_frequency, y=soil_phosphate)) + 
  geom_point() + 
  stat_smooth(method = "lm") + 
  geom_label(aes(x = 0, y = 0.06), hjust = 0, 
             label = paste("Adj R2 = ",signif(summary(phos_model)$adj.r.squared, 5), 
                           "\nIntercept =",signif(phos_model$coef[[1]],5 ), 
                           " \nSlope =",signif(phos_model$coef[[2]], 5), 
                           " \np =",signif(summary(phos_model)$coef[2, 4], 5),
                           "\nn =" ,nrow(phosphorous))) +
  ylab(expression(paste("Soil Phosphorous (", mgPsoil^-1, ")", sep = ""))) +
  xlab("Fire Frequency (Number of Fires / Year)") + 
  ggtitle("Soil Phosphorous Against Fire Frequency for All Sites") +
  theme_pubclean()

print(p1_phos)
```
# Plot mycorrhizal colonisation against functional group
```{r plot mycorrhizal colonisation functional group}
functional_group_mycorrhizae <- data_combined %>%
  group_by(functional_group) %>%
  summarise(avg_colonisation = mean(mean_colonisation))

functional_group_mycorrhizae$sample_size <- c(10, 4, 3)

kruskal_test <- kruskal.test(avg_colonisation ~ functional_group, data = functional_group_mycorrhizae)
  
# plot the average mycorrhizal colonisation per species
average_AMF <- ggplot(functional_group_mycorrhizae, aes(x=functional_group, y=avg_colonisation)) + 
  geom_bar(stat="identity", fill = ("#386cb0")) + 
  xlab("Functional Group") +
  ylab("Average AMF Colonisation (% of Root)") +
  geom_label(aes(x = 3.2, y = 25,
                   label = paste("Kruskal-Wallis Test p-value:",
                                 signif(kruskal_test$p.value, digits = 3))),
               size = 4, label.padding = unit(0.5, "lines")) +
  coord_flip() + 
  ggtitle("Average AMF Colonisation for each Functional Group") +
  geom_text(aes(label = paste("n = ", sample_size)), hjust = 1, colour = "white") +
  theme_pubclean() + 
  scale_fill_Publication()

plot(average_AMF)
```

```{r plot mycorrhizal colonisation against root traits}
# plot mycorrhizal colonisation against average root diameter
myc_diam_model <- lm(mean_colonisation ~ average_diameter_mm, data = data_combined)
p2_myc_diam <- ggplot(data_combined, aes(x=average_diameter_mm, y=mean_colonisation)) + 
  geom_point() + 
  stat_smooth(method = "lm") + 
  geom_label(aes(x = -0.05, y = 50), hjust = 0, 
             label = paste("Adj R2 = ",signif(summary(myc_diam_model)$adj.r.squared, 5), 
                           "\nIntercept =",signif(myc_diam_model$coef[[1]],5 ), 
                           " \nSlope =",signif(myc_diam_model$coef[[2]], 5), 
                           " \np =",signif(summary(myc_diam_model)$coef[2, 4], 5),
                           "\nn = 14")) +
  ylab("Average AMF Colonisation (% of Root)") +
  xlab("Average Root Diameter (mm)") + 
  ggtitle("Relationship betwen AMF Colonisation and Root Diameter") +
  theme_pubclean() + 
  scale_colour_Publication()

print(p2_myc_diam)
```

# Plot root traits against fire gradient
```{r}
root_data$fire_frequency <- as.numeric(root_data$fire_frequency)
# SRL

grass_root_data <- filter(root_data, functional_group == "grass")
SRL_grass_model <- lm(SRL ~ fire_frequency, data = grass_root_data)
summary(SRL_grass_model)

legume_root_data <- filter(root_data, functional_group == "legume")
SRL_legume_model <- lm(SRL ~ fire_frequency, data = legume_root_data)
summary(SRL_legume_model)

SRL_model <- lm(SRL ~ fire_frequency, data = root_data)
summary(SRL_model)


SRL_model <- lm(SRL ~ fire_frequency, data = root_data)
p3_SRL <- ggplot(root_data, aes(x=fire_frequency, y=SRL, colour = functional_group)) + 
  geom_point() + 
  stat_smooth(method = "lm") + 
  ylab(expression(paste("Specific Root Length (", mg^-1, ")"))) +
  xlab("Fire Frequency (Number of Fires / Year)") + 
  ggtitle("Relationship Between Specific Root Length and Fire Frequency") +
  theme_pubclean() + 
  scale_fill_Publication()

print(p3_SRL)

# RTD

RTD_grass_model <- lm(RTD ~ fire_frequency, data = grass_root_data)
summary(RTD_grass_model)

RTD_legume_model <- lm(RTD ~ fire_frequency, data = legume_root_data)
summary(RTD_legume_model)

RTD_model <- lm(RTD ~ fire_frequency, data = root_data)
summary(RTD_model)

RTD_model <- lm(RTD ~ fire_frequency, data = root_data)
p3_RTD <- ggplot(root_data, aes(x=fire_frequency, y=RTD)) + 
  geom_point() + 
  stat_smooth(method = "lm") + 
  label = paste("Adj R2 = ",signif(summary(RTD_model)$adj.r.squared, 5), 
                "\nIntercept =",signif(RTD_model$coef[[1]],5 ),
                " \nSlope =",signif(diam_model$coef[[2]], 5), 
                " \nP =",signif(summary(diam_model)$coef[2, 4], 5),
                "\nn =" ,nrow(root_data)) +
  ylab(expression(paste("Root Tissue Density (", cm^3*"g"^{-1}, ")"))) +
  xlab("Fire Frequency (Number of Fires / Year)") +
  ggtitle("Relationship Betwen Root Tissue Density and Fire Frequency") +
  theme_pubclean() + 
  scale_colour_Publication()

print(p3_RTD)

# Root Diameter

diam_grass_model <- lm(average_diameter_mm ~ fire_frequency, data = grass_root_data)
summary(diam_grass_model)

diam_legume_model <- lm(average_diameter_mm ~ fire_frequency, data = legume_root_data)
summary(diam_legume_model)

diam_model <- lm(average_diameter_mm ~ fire_frequency, data = root_data)
summary(diam_model)

diam_model <- lm(average_diameter_mm ~ fire_frequency, data = root_data)
p3_diam <- ggplot(root_data, aes(x=fire_frequency, y=average_diameter_mm)) + 
  geom_point() + 
  stat_smooth(method = "lm") + 
  geom_label(aes(x = 0, y = 25), hjust = 0, 
             label = paste("Adj R2 = ",signif(summary(diam_model)$adj.r.squared, 5), 
                           "\nIntercept =",signif(diam_model$coef[[1]],5 ), 
                           " \nSlope =",signif(diam_model$coef[[2]], 5), 
                           " \nP =",signif(summary(diam_model)$coef[2, 4], 5),
                           "\nn =" ,nrow(root_data))) +
  ylab("Average Root Diameter (mm)") +
  xlab("Fire Frequency (Number of Fires / Year)") + 
  ggtitle("Relationship Between Root Diameter and Fire Frequency") +
  theme_pubclean() + 
  scale_colour_Publication()

print(p3_diam)
```

```{r light uptake against fire frequency}
biomass_light_data$light_uptake <- as.numeric(biomass_light_data$light_uptake)
biomass_light_data$fire_frequency <- as.numeric(biomass_light_data$fire_frequency)

light_model <- lm(light_uptake ~ fire_frequency, data = biomass_light_data)
p_light <- ggplot(biomass_light_data, aes(x=fire_frequency, y=light_uptake)) + 
  geom_point() + 
  stat_smooth(method = "lm") + 
  geom_label(aes(x = -0, y = 0.3), hjust = 0, 
             label = paste("Adj R2 = ",signif(summary(light_model)$adj.r.squared, 5), 
                           "\nIntercept =",signif(light_model$coef[[1]],5 ), 
                           " \nSlope =",signif(light_model$coef[[2]], 5), 
                           " \np =",signif(summary(light_model)$coef[2, 4], 5),
                           "\nn = 11")) +
  ylab("Herbaceous Light Uptake") +
  xlab("Fire Frequency (Number of Fires / Year)") + 
  ggtitle("Relationship Between Herbaceous Light Uptake and Fire Frequency") +
  theme_pubclean()

print(p_light)

```

